import { Chat, Message } from './types';

export const MOCK_CHATS: Chat[] = [
  {
    id: '1',
    participants: ['user1', 'user2'],
    participantNames: ['Алексей', 'Мария'],
    messages: [],
    overallRisk: 'safe',
    lastActivity: Date.now() - 3600000,
  },
  {
    id: '2',
    participants: ['user3', 'user4'],
    participantNames: ['Дмитрий', 'Анна'],
    messages: [],
    overallRisk: 'safe',
    lastActivity: Date.now() - 7200000,
  },
  {
    id: '3',
    participants: ['user5', 'user6'],
    participantNames: ['Иван', 'Ольга'],
    messages: [],
    overallRisk: 'safe',
    lastActivity: Date.now() - 10800000,
  },
  {
    id: 'group1',
    participants: ['user1', 'user2', 'user7', 'user8', 'user9', 'user10', 'user11', 'user12'],
    participantNames: ['Алексей', 'Мария', 'Сергей', 'Елена', 'Николай', 'Анастасия', 'Максим', 'Виктория'],
    messages: [],
    overallRisk: 'safe',
    lastActivity: Date.now() - 1800000,
    isGroup: true,
    groupName: '5А класс',
    groupType: 'class',
    groupDescription: 'Чат класса 5А',
    adminIds: ['user1'],
  },
  {
    id: 'group2',
    participants: ['user3', 'user4', 'user13', 'user14', 'user15'],
    participantNames: ['Дмитрий', 'Анна', 'Павел', 'Юлия', 'Артём'],
    messages: [],
    overallRisk: 'safe',
    lastActivity: Date.now() - 5400000,
    isGroup: true,
    groupName: 'Футбольная секция',
    groupType: 'club',
    groupDescription: 'Группа для футбольной секции',
    adminIds: ['user3'],
  },
  {
    id: 'group3',
    participants: ['user5', 'user6', 'user16', 'user17', 'user18', 'user19'],
    participantNames: ['Иван', 'Ольга', 'Денис', 'Татьяна', 'Роман', 'Ирина'],
    messages: [],
    overallRisk: 'safe',
    lastActivity: Date.now() - 9000000,
    isGroup: true,
    groupName: 'Математический кружок',
    groupType: 'group',
    groupDescription: 'Дополнительные занятия по математике',
    adminIds: ['user5', 'user6'],
  },
];

export const INITIAL_MESSAGES: Record<string, Message[]> = {
  '1': [
    {
      id: 'm1',
      text: 'Привет! Как дела?',
      senderId: 'user1',
      senderName: 'Алексей',
      timestamp: Date.now() - 3600000,
      analyzed: false,
    },
  ],
  '2': [
    {
      id: 'm2',
      text: 'Здравствуй',
      senderId: 'user3',
      senderName: 'Дмитрий',
      timestamp: Date.now() - 7200000,
      analyzed: false,
    },
  ],
  '3': [],
  'group1': [
    {
      id: 'gm1',
      text: 'Привет всем! Не забудьте про домашнее задание по математике',
      senderId: 'user1',
      senderName: 'Алексей',
      timestamp: Date.now() - 1800000,
      analyzed: false,
    },
    {
      id: 'gm2',
      text: 'Спасибо за напоминание!',
      senderId: 'user2',
      senderName: 'Мария',
      timestamp: Date.now() - 1500000,
      analyzed: false,
    },
  ],
  'group2': [
    {
      id: 'gm3',
      text: 'Тренировка завтра в 16:00',
      senderId: 'user3',
      senderName: 'Дмитрий',
      timestamp: Date.now() - 5400000,
      analyzed: false,
    },
  ],
  'group3': [
    {
      id: 'gm4',
      text: 'На следующей неделе начнём изучать геометрию',
      senderId: 'user5',
      senderName: 'Иван',
      timestamp: Date.now() - 9000000,
      analyzed: false,
    },
  ],
};
