# GitHub Sponsors configuration
# Примечание: GitHub Sponsors недоступен в Грузии
# Используем альтернативные платформы

# github: # Недоступно в Грузии - используем custom платформы
custom:
  # PayPal - работает везде, включая Грузию
  - 'https://paypal.me/kikuapp'
  
  # Patreon - работает в Грузии
  - 'https://www.patreon.com/kiku'
  
  # Buy Me a Coffee - работает в Грузии
  - 'https://www.buymeacoffee.com/kiku'
  
  # Ko-fi - работает в Грузии
  - 'https://ko-fi.com/kiku'
  
  # Прямые переводы (когда настроите)
  # - 'https://kiku.app/sponsor'

