name: 🚀 Enhancement
description: Suggest an improvement to an existing feature
title: "[Enhancement]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an enhancement! This template is for improvements to existing features.

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: Describe how the feature currently works
      placeholder: Explain the current implementation...
    validations:
      required: true

  - type: textarea
    id: proposed-improvement
    attributes:
      label: Proposed Improvement
      description: Describe how you'd like to enhance the existing feature
      placeholder: Explain what should be improved and how...
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What are the benefits of this enhancement?
      placeholder: |
        - Improved performance
        - Better user experience
        - Easier to use
        - More maintainable code
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: How many users would benefit from this enhancement?
      options:
        - Small - Affects specific use cases
        - Medium - Affects several users
        - Large - Affects most users
        - Critical - Affects all users
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Suggestions
      description: Do you have any suggestions for how this could be implemented?
      placeholder: Optional technical details or implementation ideas...

  - type: textarea
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Would this enhancement introduce any breaking changes?
      placeholder: Yes/No and explain if yes...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the enhancement
      placeholder: Any additional information that might be helpful...
